version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    # Don't check error returns for logging/audit methods (best-effort)
    exclude-functions:
      # Audit service methods (best-effort logging)
      - (*github.com/felixgeelhaar/bridge/internal/domain/governance.AuditService).LogWorkflowStarted
      - (*github.com/felixgeelhaar/bridge/internal/domain/governance.AuditService).LogWorkflowCompleted
      - (*github.com/felixgeelhaar/bridge/internal/domain/governance.AuditService).LogWorkflowFailed
      - (*github.com/felixgeelhaar/bridge/internal/domain/governance.AuditService).LogAgentCalled
      - (*github.com/felixgeelhaar/bridge/internal/domain/governance.AuditService).LogPolicyEvaluated
      - (*github.com/felixgeelhaar/bridge/internal/domain/governance.AuditService).LogPolicyViolation
      # Workflow service state updates (best-effort during error paths)
      - (*github.com/felixgeelhaar/bridge/internal/domain/workflow.Service).UpdateRun
      - (*github.com/felixgeelhaar/bridge/internal/domain/workflow.Service).UpdateStep
      # Test helpers
      - (github.com/felixgeelhaar/bolt.Logger).Log
      - (*encoding/json.Encoder).Encode

issues:
  # Don't check test files as strictly
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
