// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAgents = `-- name: CountAgents :one
SELECT COUNT(*) FROM agents
`

func (q *Queries) CountAgents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAgents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (
    id, name, description, provider, model, system_prompt,
    max_tokens, temperature, capabilities, metadata, active,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, name, description, provider, model, system_prompt, max_tokens, temperature, capabilities, metadata, active, created_at, updated_at
`

type CreateAgentParams struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	Provider     string             `json:"provider"`
	Model        string             `json:"model"`
	SystemPrompt *string            `json:"system_prompt"`
	MaxTokens    *int32             `json:"max_tokens"`
	Temperature  pgtype.Numeric     `json:"temperature"`
	Capabilities []string           `json:"capabilities"`
	Metadata     []byte             `json:"metadata"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Provider,
		arg.Model,
		arg.SystemPrompt,
		arg.MaxTokens,
		arg.Temperature,
		arg.Capabilities,
		arg.Metadata,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Model,
		&i.SystemPrompt,
		&i.MaxTokens,
		&i.Temperature,
		&i.Capabilities,
		&i.Metadata,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents
WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, description, provider, model, system_prompt, max_tokens, temperature, capabilities, metadata, active, created_at, updated_at FROM agents
WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Model,
		&i.SystemPrompt,
		&i.MaxTokens,
		&i.Temperature,
		&i.Capabilities,
		&i.Metadata,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentByName = `-- name: GetAgentByName :one
SELECT id, name, description, provider, model, system_prompt, max_tokens, temperature, capabilities, metadata, active, created_at, updated_at FROM agents
WHERE name = $1
`

func (q *Queries) GetAgentByName(ctx context.Context, name string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByName, name)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Model,
		&i.SystemPrompt,
		&i.MaxTokens,
		&i.Temperature,
		&i.Capabilities,
		&i.Metadata,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAgents = `-- name: ListActiveAgents :many
SELECT id, name, description, provider, model, system_prompt, max_tokens, temperature, capabilities, metadata, active, created_at, updated_at FROM agents
WHERE active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListActiveAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listActiveAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Provider,
			&i.Model,
			&i.SystemPrompt,
			&i.MaxTokens,
			&i.Temperature,
			&i.Capabilities,
			&i.Metadata,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, description, provider, model, system_prompt, max_tokens, temperature, capabilities, metadata, active, created_at, updated_at FROM agents
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListAgentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Provider,
			&i.Model,
			&i.SystemPrompt,
			&i.MaxTokens,
			&i.Temperature,
			&i.Capabilities,
			&i.Metadata,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET
    name = $2,
    description = $3,
    provider = $4,
    model = $5,
    system_prompt = $6,
    max_tokens = $7,
    temperature = $8,
    capabilities = $9,
    metadata = $10,
    active = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, provider, model, system_prompt, max_tokens, temperature, capabilities, metadata, active, created_at, updated_at
`

type UpdateAgentParams struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Description  *string        `json:"description"`
	Provider     string         `json:"provider"`
	Model        string         `json:"model"`
	SystemPrompt *string        `json:"system_prompt"`
	MaxTokens    *int32         `json:"max_tokens"`
	Temperature  pgtype.Numeric `json:"temperature"`
	Capabilities []string       `json:"capabilities"`
	Metadata     []byte         `json:"metadata"`
	Active       bool           `json:"active"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Provider,
		arg.Model,
		arg.SystemPrompt,
		arg.MaxTokens,
		arg.Temperature,
		arg.Capabilities,
		arg.Metadata,
		arg.Active,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Model,
		&i.SystemPrompt,
		&i.MaxTokens,
		&i.Temperature,
		&i.Capabilities,
		&i.Metadata,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
