// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approval_requests.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApprovalRequest = `-- name: CreateApprovalRequest :one
INSERT INTO approval_requests (
    id, run_id, step_name, status, requested_by,
    approved_by, rejected_by, reason, expires_at, decided_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, run_id, step_name, status, requested_by, approved_by, rejected_by, reason, expires_at, decided_at, created_at
`

type CreateApprovalRequestParams struct {
	ID          string             `json:"id"`
	RunID       string             `json:"run_id"`
	StepName    string             `json:"step_name"`
	Status      string             `json:"status"`
	RequestedBy *string            `json:"requested_by"`
	ApprovedBy  *string            `json:"approved_by"`
	RejectedBy  *string            `json:"rejected_by"`
	Reason      *string            `json:"reason"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	DecidedAt   pgtype.Timestamptz `json:"decided_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateApprovalRequest(ctx context.Context, arg CreateApprovalRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, createApprovalRequest,
		arg.ID,
		arg.RunID,
		arg.StepName,
		arg.Status,
		arg.RequestedBy,
		arg.ApprovedBy,
		arg.RejectedBy,
		arg.Reason,
		arg.ExpiresAt,
		arg.DecidedAt,
		arg.CreatedAt,
	)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepName,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.Reason,
		&i.ExpiresAt,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteApprovalRequest = `-- name: DeleteApprovalRequest :exec
DELETE FROM approval_requests
WHERE id = $1
`

func (q *Queries) DeleteApprovalRequest(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteApprovalRequest, id)
	return err
}

const expireApprovalRequests = `-- name: ExpireApprovalRequests :exec
UPDATE approval_requests
SET status = 'expired', decided_at = NOW()
WHERE status = 'pending' AND expires_at < NOW()
`

func (q *Queries) ExpireApprovalRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireApprovalRequests)
	return err
}

const getApprovalRequest = `-- name: GetApprovalRequest :one
SELECT id, run_id, step_name, status, requested_by, approved_by, rejected_by, reason, expires_at, decided_at, created_at FROM approval_requests
WHERE id = $1
`

func (q *Queries) GetApprovalRequest(ctx context.Context, id string) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getApprovalRequest, id)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepName,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.Reason,
		&i.ExpiresAt,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApprovalRequestByRunID = `-- name: GetApprovalRequestByRunID :one
SELECT id, run_id, step_name, status, requested_by, approved_by, rejected_by, reason, expires_at, decided_at, created_at FROM approval_requests
WHERE run_id = $1 AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetApprovalRequestByRunID(ctx context.Context, runID string) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getApprovalRequestByRunID, runID)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepName,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.Reason,
		&i.ExpiresAt,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovalRequestsByRunID = `-- name: ListApprovalRequestsByRunID :many
SELECT id, run_id, step_name, status, requested_by, approved_by, rejected_by, reason, expires_at, decided_at, created_at FROM approval_requests
WHERE run_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListApprovalRequestsByRunID(ctx context.Context, runID string) ([]ApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listApprovalRequestsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRequest{}
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepName,
			&i.Status,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.RejectedBy,
			&i.Reason,
			&i.ExpiresAt,
			&i.DecidedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalRequests = `-- name: ListPendingApprovalRequests :many
SELECT id, run_id, step_name, status, requested_by, approved_by, rejected_by, reason, expires_at, decided_at, created_at FROM approval_requests
WHERE status = 'pending'
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at ASC
`

func (q *Queries) ListPendingApprovalRequests(ctx context.Context) ([]ApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listPendingApprovalRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRequest{}
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepName,
			&i.Status,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.RejectedBy,
			&i.Reason,
			&i.ExpiresAt,
			&i.DecidedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApprovalRequest = `-- name: UpdateApprovalRequest :one
UPDATE approval_requests
SET
    status = $2,
    approved_by = $3,
    rejected_by = $4,
    reason = $5,
    decided_at = $6
WHERE id = $1
RETURNING id, run_id, step_name, status, requested_by, approved_by, rejected_by, reason, expires_at, decided_at, created_at
`

type UpdateApprovalRequestParams struct {
	ID         string             `json:"id"`
	Status     string             `json:"status"`
	ApprovedBy *string            `json:"approved_by"`
	RejectedBy *string            `json:"rejected_by"`
	Reason     *string            `json:"reason"`
	DecidedAt  pgtype.Timestamptz `json:"decided_at"`
}

func (q *Queries) UpdateApprovalRequest(ctx context.Context, arg UpdateApprovalRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, updateApprovalRequest,
		arg.ID,
		arg.Status,
		arg.ApprovedBy,
		arg.RejectedBy,
		arg.Reason,
		arg.DecidedAt,
	)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepName,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.RejectedBy,
		&i.Reason,
		&i.ExpiresAt,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}
