// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT COUNT(*) FROM audit_events
`

func (q *Queries) CountAuditEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    id, type, actor, resource_type, resource_id, action, details, timestamp
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, type, actor, resource_type, resource_id, action, details, timestamp
`

type CreateAuditEventParams struct {
	ID           string             `json:"id"`
	Type         string             `json:"type"`
	Actor        *string            `json:"actor"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   *string            `json:"resource_id"`
	Action       string             `json:"action"`
	Details      []byte             `json:"details"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.ID,
		arg.Type,
		arg.Actor,
		arg.ResourceType,
		arg.ResourceID,
		arg.Action,
		arg.Details,
		arg.Timestamp,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Actor,
		&i.ResourceType,
		&i.ResourceID,
		&i.Action,
		&i.Details,
		&i.Timestamp,
	)
	return i, err
}

const deleteOldAuditEvents = `-- name: DeleteOldAuditEvents :exec
DELETE FROM audit_events
WHERE timestamp < $1
`

func (q *Queries) DeleteOldAuditEvents(ctx context.Context, timestamp pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldAuditEvents, timestamp)
	return err
}

const getAuditEvent = `-- name: GetAuditEvent :one
SELECT id, type, actor, resource_type, resource_id, action, details, timestamp FROM audit_events
WHERE id = $1
`

func (q *Queries) GetAuditEvent(ctx context.Context, id string) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, getAuditEvent, id)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Actor,
		&i.ResourceType,
		&i.ResourceID,
		&i.Action,
		&i.Details,
		&i.Timestamp,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, type, actor, resource_type, resource_id, action, details, timestamp FROM audit_events
ORDER BY timestamp DESC
LIMIT $1 OFFSET $2
`

type ListAuditEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Actor,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.Details,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByActor = `-- name: ListAuditEventsByActor :many
SELECT id, type, actor, resource_type, resource_id, action, details, timestamp FROM audit_events
WHERE actor = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListAuditEventsByActorParams struct {
	Actor  *string `json:"actor"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
}

func (q *Queries) ListAuditEventsByActor(ctx context.Context, arg ListAuditEventsByActorParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByActor, arg.Actor, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Actor,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.Details,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByResource = `-- name: ListAuditEventsByResource :many
SELECT id, type, actor, resource_type, resource_id, action, details, timestamp FROM audit_events
WHERE resource_type = $1 AND resource_id = $2
ORDER BY timestamp DESC
LIMIT $3 OFFSET $4
`

type ListAuditEventsByResourceParams struct {
	ResourceType *string `json:"resource_type"`
	ResourceID   *string `json:"resource_id"`
	Limit        int32   `json:"limit"`
	Offset       int32   `json:"offset"`
}

func (q *Queries) ListAuditEventsByResource(ctx context.Context, arg ListAuditEventsByResourceParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByResource,
		arg.ResourceType,
		arg.ResourceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Actor,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.Details,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByType = `-- name: ListAuditEventsByType :many
SELECT id, type, actor, resource_type, resource_id, action, details, timestamp FROM audit_events
WHERE type = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListAuditEventsByTypeParams struct {
	Type   string `json:"type"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListAuditEventsByType(ctx context.Context, arg ListAuditEventsByTypeParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Actor,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.Details,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
