// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	Provider     string             `json:"provider"`
	Model        string             `json:"model"`
	SystemPrompt *string            `json:"system_prompt"`
	MaxTokens    *int32             `json:"max_tokens"`
	Temperature  pgtype.Numeric     `json:"temperature"`
	Capabilities []string           `json:"capabilities"`
	Metadata     []byte             `json:"metadata"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ApprovalRequest struct {
	ID          string             `json:"id"`
	RunID       string             `json:"run_id"`
	StepName    string             `json:"step_name"`
	Status      string             `json:"status"`
	RequestedBy *string            `json:"requested_by"`
	ApprovedBy  *string            `json:"approved_by"`
	RejectedBy  *string            `json:"rejected_by"`
	Reason      *string            `json:"reason"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	DecidedAt   pgtype.Timestamptz `json:"decided_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuditEvent struct {
	ID           string             `json:"id"`
	Type         string             `json:"type"`
	Actor        *string            `json:"actor"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   *string            `json:"resource_id"`
	Action       string             `json:"action"`
	Details      []byte             `json:"details"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
}

type PolicyBundle struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Version     string             `json:"version"`
	Description *string            `json:"description"`
	Rules       []byte             `json:"rules"`
	Checksum    *string            `json:"checksum"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type StepRun struct {
	ID               string             `json:"id"`
	RunID            string             `json:"run_id"`
	StepIndex        int32              `json:"step_index"`
	Name             string             `json:"name"`
	AgentID          *string            `json:"agent_id"`
	Status           string             `json:"status"`
	Input            []byte             `json:"input"`
	Output           []byte             `json:"output"`
	RequiresApproval bool               `json:"requires_approval"`
	TimeoutSeconds   *int32             `json:"timeout_seconds"`
	MaxRetries       *int32             `json:"max_retries"`
	RetryCount       *int32             `json:"retry_count"`
	Error            *string            `json:"error"`
	TokensIn         *int32             `json:"tokens_in"`
	TokensOut        *int32             `json:"tokens_out"`
	StepOrder        int32              `json:"step_order"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type WorkflowDefinition struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Version     string             `json:"version"`
	Description *string            `json:"description"`
	Config      []byte             `json:"config"`
	Checksum    *string            `json:"checksum"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkflowRun struct {
	ID               string             `json:"id"`
	WorkflowID       string             `json:"workflow_id"`
	WorkflowName     string             `json:"workflow_name"`
	WorkflowVersion  string             `json:"workflow_version"`
	Status           string             `json:"status"`
	CurrentStepIndex int32              `json:"current_step_index"`
	Context          []byte             `json:"context"`
	TriggeredBy      *string            `json:"triggered_by"`
	TriggerData      []byte             `json:"trigger_data"`
	Error            *string            `json:"error"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
