// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policy_bundles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPolicyBundles = `-- name: CountPolicyBundles :one
SELECT COUNT(*) FROM policy_bundles
`

func (q *Queries) CountPolicyBundles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPolicyBundles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPolicyBundle = `-- name: CreatePolicyBundle :one
INSERT INTO policy_bundles (
    id, name, version, description, rules, checksum, active,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, version, description, rules, checksum, active, created_at, updated_at
`

type CreatePolicyBundleParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Version     string             `json:"version"`
	Description *string            `json:"description"`
	Rules       []byte             `json:"rules"`
	Checksum    *string            `json:"checksum"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePolicyBundle(ctx context.Context, arg CreatePolicyBundleParams) (PolicyBundle, error) {
	row := q.db.QueryRow(ctx, createPolicyBundle,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Rules,
		arg.Checksum,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PolicyBundle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Rules,
		&i.Checksum,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePolicyBundle = `-- name: DeletePolicyBundle :exec
DELETE FROM policy_bundles
WHERE id = $1
`

func (q *Queries) DeletePolicyBundle(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePolicyBundle, id)
	return err
}

const getPolicyBundle = `-- name: GetPolicyBundle :one
SELECT id, name, version, description, rules, checksum, active, created_at, updated_at FROM policy_bundles
WHERE id = $1
`

func (q *Queries) GetPolicyBundle(ctx context.Context, id string) (PolicyBundle, error) {
	row := q.db.QueryRow(ctx, getPolicyBundle, id)
	var i PolicyBundle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Rules,
		&i.Checksum,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicyBundleByName = `-- name: GetPolicyBundleByName :one
SELECT id, name, version, description, rules, checksum, active, created_at, updated_at FROM policy_bundles
WHERE name = $1
`

func (q *Queries) GetPolicyBundleByName(ctx context.Context, name string) (PolicyBundle, error) {
	row := q.db.QueryRow(ctx, getPolicyBundleByName, name)
	var i PolicyBundle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Rules,
		&i.Checksum,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePolicyBundles = `-- name: ListActivePolicyBundles :many
SELECT id, name, version, description, rules, checksum, active, created_at, updated_at FROM policy_bundles
WHERE active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListActivePolicyBundles(ctx context.Context) ([]PolicyBundle, error) {
	rows, err := q.db.Query(ctx, listActivePolicyBundles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyBundle{}
	for rows.Next() {
		var i PolicyBundle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Rules,
			&i.Checksum,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyBundles = `-- name: ListPolicyBundles :many
SELECT id, name, version, description, rules, checksum, active, created_at, updated_at FROM policy_bundles
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListPolicyBundlesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPolicyBundles(ctx context.Context, arg ListPolicyBundlesParams) ([]PolicyBundle, error) {
	rows, err := q.db.Query(ctx, listPolicyBundles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PolicyBundle{}
	for rows.Next() {
		var i PolicyBundle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Rules,
			&i.Checksum,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicyBundle = `-- name: UpdatePolicyBundle :one
UPDATE policy_bundles
SET
    name = $2,
    version = $3,
    description = $4,
    rules = $5,
    checksum = $6,
    active = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, version, description, rules, checksum, active, created_at, updated_at
`

type UpdatePolicyBundleParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Version     string  `json:"version"`
	Description *string `json:"description"`
	Rules       []byte  `json:"rules"`
	Checksum    *string `json:"checksum"`
	Active      bool    `json:"active"`
}

func (q *Queries) UpdatePolicyBundle(ctx context.Context, arg UpdatePolicyBundleParams) (PolicyBundle, error) {
	row := q.db.QueryRow(ctx, updatePolicyBundle,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Rules,
		arg.Checksum,
		arg.Active,
	)
	var i PolicyBundle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Rules,
		&i.Checksum,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
