// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveWorkflowRuns(ctx context.Context) (int64, error)
	CountAgents(ctx context.Context) (int64, error)
	CountAuditEvents(ctx context.Context) (int64, error)
	CountPolicyBundles(ctx context.Context) (int64, error)
	CountWorkflowDefinitions(ctx context.Context) (int64, error)
	CountWorkflowRuns(ctx context.Context, workflowID string) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateApprovalRequest(ctx context.Context, arg CreateApprovalRequestParams) (ApprovalRequest, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreatePolicyBundle(ctx context.Context, arg CreatePolicyBundleParams) (PolicyBundle, error)
	CreateStepRun(ctx context.Context, arg CreateStepRunParams) (StepRun, error)
	CreateWorkflowDefinition(ctx context.Context, arg CreateWorkflowDefinitionParams) (WorkflowDefinition, error)
	CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error)
	DeleteAgent(ctx context.Context, id string) error
	DeleteApprovalRequest(ctx context.Context, id string) error
	DeleteOldAuditEvents(ctx context.Context, timestamp pgtype.Timestamptz) error
	DeletePolicyBundle(ctx context.Context, id string) error
	DeleteStepRunsByRunID(ctx context.Context, runID string) error
	DeleteWorkflowDefinition(ctx context.Context, id string) error
	ExpireApprovalRequests(ctx context.Context) error
	GetAgent(ctx context.Context, id string) (Agent, error)
	GetAgentByName(ctx context.Context, name string) (Agent, error)
	GetApprovalRequest(ctx context.Context, id string) (ApprovalRequest, error)
	GetApprovalRequestByRunID(ctx context.Context, runID string) (ApprovalRequest, error)
	GetAuditEvent(ctx context.Context, id string) (AuditEvent, error)
	GetPolicyBundle(ctx context.Context, id string) (PolicyBundle, error)
	GetPolicyBundleByName(ctx context.Context, name string) (PolicyBundle, error)
	GetStepRun(ctx context.Context, id string) (StepRun, error)
	GetWorkflowDefinition(ctx context.Context, id string) (WorkflowDefinition, error)
	GetWorkflowDefinitionByName(ctx context.Context, name string) (WorkflowDefinition, error)
	GetWorkflowRun(ctx context.Context, id string) (WorkflowRun, error)
	ListActiveAgents(ctx context.Context) ([]Agent, error)
	ListActivePolicyBundles(ctx context.Context) ([]PolicyBundle, error)
	ListActiveWorkflowRuns(ctx context.Context) ([]WorkflowRun, error)
	ListAgents(ctx context.Context, arg ListAgentsParams) ([]Agent, error)
	ListApprovalRequestsByRunID(ctx context.Context, runID string) ([]ApprovalRequest, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListAuditEventsByActor(ctx context.Context, arg ListAuditEventsByActorParams) ([]AuditEvent, error)
	ListAuditEventsByResource(ctx context.Context, arg ListAuditEventsByResourceParams) ([]AuditEvent, error)
	ListAuditEventsByType(ctx context.Context, arg ListAuditEventsByTypeParams) ([]AuditEvent, error)
	ListPendingApprovalRequests(ctx context.Context) ([]ApprovalRequest, error)
	ListPolicyBundles(ctx context.Context, arg ListPolicyBundlesParams) ([]PolicyBundle, error)
	ListStepRunsByRunID(ctx context.Context, runID string) ([]StepRun, error)
	ListWorkflowDefinitions(ctx context.Context, arg ListWorkflowDefinitionsParams) ([]WorkflowDefinition, error)
	ListWorkflowRuns(ctx context.Context, arg ListWorkflowRunsParams) ([]WorkflowRun, error)
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error)
	UpdateApprovalRequest(ctx context.Context, arg UpdateApprovalRequestParams) (ApprovalRequest, error)
	UpdatePolicyBundle(ctx context.Context, arg UpdatePolicyBundleParams) (PolicyBundle, error)
	UpdateStepRun(ctx context.Context, arg UpdateStepRunParams) (StepRun, error)
	UpdateWorkflowDefinition(ctx context.Context, arg UpdateWorkflowDefinitionParams) (WorkflowDefinition, error)
	UpdateWorkflowRun(ctx context.Context, arg UpdateWorkflowRunParams) (WorkflowRun, error)
}

var _ Querier = (*Queries)(nil)
