// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_definitions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkflowDefinitions = `-- name: CountWorkflowDefinitions :one
SELECT COUNT(*) FROM workflow_definitions
`

func (q *Queries) CountWorkflowDefinitions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflowDefinitions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkflowDefinition = `-- name: CreateWorkflowDefinition :one
INSERT INTO workflow_definitions (
    id, name, version, description, config, checksum, metadata, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, version, description, config, checksum, metadata, created_at, updated_at
`

type CreateWorkflowDefinitionParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Version     string             `json:"version"`
	Description *string            `json:"description"`
	Config      []byte             `json:"config"`
	Checksum    *string            `json:"checksum"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateWorkflowDefinition(ctx context.Context, arg CreateWorkflowDefinitionParams) (WorkflowDefinition, error) {
	row := q.db.QueryRow(ctx, createWorkflowDefinition,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Config,
		arg.Checksum,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WorkflowDefinition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Config,
		&i.Checksum,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkflowDefinition = `-- name: DeleteWorkflowDefinition :exec
DELETE FROM workflow_definitions
WHERE id = $1
`

func (q *Queries) DeleteWorkflowDefinition(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWorkflowDefinition, id)
	return err
}

const getWorkflowDefinition = `-- name: GetWorkflowDefinition :one
SELECT id, name, version, description, config, checksum, metadata, created_at, updated_at FROM workflow_definitions
WHERE id = $1
`

func (q *Queries) GetWorkflowDefinition(ctx context.Context, id string) (WorkflowDefinition, error) {
	row := q.db.QueryRow(ctx, getWorkflowDefinition, id)
	var i WorkflowDefinition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Config,
		&i.Checksum,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowDefinitionByName = `-- name: GetWorkflowDefinitionByName :one
SELECT id, name, version, description, config, checksum, metadata, created_at, updated_at FROM workflow_definitions
WHERE name = $1
`

func (q *Queries) GetWorkflowDefinitionByName(ctx context.Context, name string) (WorkflowDefinition, error) {
	row := q.db.QueryRow(ctx, getWorkflowDefinitionByName, name)
	var i WorkflowDefinition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Config,
		&i.Checksum,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflowDefinitions = `-- name: ListWorkflowDefinitions :many
SELECT id, name, version, description, config, checksum, metadata, created_at, updated_at FROM workflow_definitions
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListWorkflowDefinitionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWorkflowDefinitions(ctx context.Context, arg ListWorkflowDefinitionsParams) ([]WorkflowDefinition, error) {
	rows, err := q.db.Query(ctx, listWorkflowDefinitions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowDefinition{}
	for rows.Next() {
		var i WorkflowDefinition
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Config,
			&i.Checksum,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowDefinition = `-- name: UpdateWorkflowDefinition :one
UPDATE workflow_definitions
SET
    name = $2,
    version = $3,
    description = $4,
    config = $5,
    checksum = $6,
    metadata = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, version, description, config, checksum, metadata, created_at, updated_at
`

type UpdateWorkflowDefinitionParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Version     string  `json:"version"`
	Description *string `json:"description"`
	Config      []byte  `json:"config"`
	Checksum    *string `json:"checksum"`
	Metadata    []byte  `json:"metadata"`
}

func (q *Queries) UpdateWorkflowDefinition(ctx context.Context, arg UpdateWorkflowDefinitionParams) (WorkflowDefinition, error) {
	row := q.db.QueryRow(ctx, updateWorkflowDefinition,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Config,
		arg.Checksum,
		arg.Metadata,
	)
	var i WorkflowDefinition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Config,
		&i.Checksum,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
