// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveWorkflowRuns = `-- name: CountActiveWorkflowRuns :one
SELECT COUNT(*) FROM workflow_runs
WHERE status NOT IN ('completed', 'failed', 'cancelled')
`

func (q *Queries) CountActiveWorkflowRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWorkflowRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkflowRuns = `-- name: CountWorkflowRuns :one
SELECT COUNT(*) FROM workflow_runs
WHERE workflow_id = $1
`

func (q *Queries) CountWorkflowRuns(ctx context.Context, workflowID string) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflowRuns, workflowID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO workflow_runs (
    id, workflow_id, workflow_name, workflow_version, status,
    current_step_index, context, triggered_by, trigger_data,
    error, started_at, completed_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, workflow_id, workflow_name, workflow_version, status, current_step_index, context, triggered_by, trigger_data, error, started_at, completed_at, created_at, updated_at
`

type CreateWorkflowRunParams struct {
	ID               string             `json:"id"`
	WorkflowID       string             `json:"workflow_id"`
	WorkflowName     string             `json:"workflow_name"`
	WorkflowVersion  string             `json:"workflow_version"`
	Status           string             `json:"status"`
	CurrentStepIndex int32              `json:"current_step_index"`
	Context          []byte             `json:"context"`
	TriggeredBy      *string            `json:"triggered_by"`
	TriggerData      []byte             `json:"trigger_data"`
	Error            *string            `json:"error"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.ID,
		arg.WorkflowID,
		arg.WorkflowName,
		arg.WorkflowVersion,
		arg.Status,
		arg.CurrentStepIndex,
		arg.Context,
		arg.TriggeredBy,
		arg.TriggerData,
		arg.Error,
		arg.StartedAt,
		arg.CompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowName,
		&i.WorkflowVersion,
		&i.Status,
		&i.CurrentStepIndex,
		&i.Context,
		&i.TriggeredBy,
		&i.TriggerData,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, workflow_id, workflow_name, workflow_version, status, current_step_index, context, triggered_by, trigger_data, error, started_at, completed_at, created_at, updated_at FROM workflow_runs
WHERE id = $1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id string) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowName,
		&i.WorkflowVersion,
		&i.Status,
		&i.CurrentStepIndex,
		&i.Context,
		&i.TriggeredBy,
		&i.TriggerData,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWorkflowRuns = `-- name: ListActiveWorkflowRuns :many
SELECT id, workflow_id, workflow_name, workflow_version, status, current_step_index, context, triggered_by, trigger_data, error, started_at, completed_at, created_at, updated_at FROM workflow_runs
WHERE status NOT IN ('completed', 'failed', 'cancelled')
ORDER BY created_at DESC
`

func (q *Queries) ListActiveWorkflowRuns(ctx context.Context) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listActiveWorkflowRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowRun{}
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.WorkflowName,
			&i.WorkflowVersion,
			&i.Status,
			&i.CurrentStepIndex,
			&i.Context,
			&i.TriggeredBy,
			&i.TriggerData,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
SELECT id, workflow_id, workflow_name, workflow_version, status, current_step_index, context, triggered_by, trigger_data, error, started_at, completed_at, created_at, updated_at FROM workflow_runs
WHERE workflow_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkflowRunsParams struct {
	WorkflowID string `json:"workflow_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListWorkflowRuns(ctx context.Context, arg ListWorkflowRunsParams) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listWorkflowRuns, arg.WorkflowID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowRun{}
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.WorkflowName,
			&i.WorkflowVersion,
			&i.Status,
			&i.CurrentStepIndex,
			&i.Context,
			&i.TriggeredBy,
			&i.TriggerData,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowRun = `-- name: UpdateWorkflowRun :one
UPDATE workflow_runs
SET
    status = $2,
    current_step_index = $3,
    context = $4,
    error = $5,
    started_at = $6,
    completed_at = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, workflow_id, workflow_name, workflow_version, status, current_step_index, context, triggered_by, trigger_data, error, started_at, completed_at, created_at, updated_at
`

type UpdateWorkflowRunParams struct {
	ID               string             `json:"id"`
	Status           string             `json:"status"`
	CurrentStepIndex int32              `json:"current_step_index"`
	Context          []byte             `json:"context"`
	Error            *string            `json:"error"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateWorkflowRun(ctx context.Context, arg UpdateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, updateWorkflowRun,
		arg.ID,
		arg.Status,
		arg.CurrentStepIndex,
		arg.Context,
		arg.Error,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowName,
		&i.WorkflowVersion,
		&i.Status,
		&i.CurrentStepIndex,
		&i.Context,
		&i.TriggeredBy,
		&i.TriggerData,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
